### ISSUE TITLE
Happy Birthday for 2024

### ISSUE THREAD

**Issue by Xuanwo** [Xuanwo/Xuanwo#1]
This issue celebrates my birthday in 2024.

*I wrote a post for this: https://xuanwo.io/2024/06-baking-an-open-source-cake/*

In short, I will submit a PR for anyone who left their open source rust project. This issue will track the progress.

## Context

https://x.com/OnlyXuanwo/status/1814625279085851069

![image](https://github.com/user-attachments/assets/dc08248a-d869-4faf-95eb-8fe1a2f5e69a)

## Projects

- [x] https://github.com/ho-229/cloud-filter-rs
  - [x] https://github.com/ho-229/cloud-filter-rs/pull/4
  - [x] https://github.com/ho-229/cloud-filter-rs/pull/5
- [x] https://github.com/PoiScript/orgize
  - [x] https://github.com/PoiScript/orgize/pull/82
- [x] https://github.com/apache/datafusion-comet
  - [x] https://github.com/apache/datafusion-comet/issues/698
  - [x] https://github.com/apache/datafusion-comet/pull/699
  - [x] https://github.com/apache/datafusion-comet/issues/700
  - [x] https://github.com/apache/datafusion-comet/pull/701
  - [x] https://github.com/apache/datafusion-comet/pull/702
- [x] https://github.com/compio-rs/compio
  - [x] https://github.com/compio-rs/compio/pull/280
- [x] https://github.com/the-alchemists-of-arland/gray-matter-rs
  - [x] https://github.com/the-alchemists-of-arland/gray-matter-rs/issues/20
  - [x] https://github.com/the-alchemists-of-arland/gray-matter-rs/pull/21
- [x] https://github.com/obi1kenobi/cargo-semver-checks
  - [x] https://github.com/obi1kenobi/cargo-semver-checks/issues/823
  - [x] https://github.com/obi1kenobi/trustfall-rustdoc-adapter/pull/338
- [x] https://github.com/isographlabs/isograph
  - [x] https://github.com/isographlabs/isograph/pull/89
- [x] https://github.com/MemoriesOfTime/raknet-rs
  - [x] https://github.com/MemoriesOfTime/raknet-rs/pull/5
- [x] https://github.com/sonhmai/rust-sqlite
  - [x] https://github.com/sonhmai/rust-sqlite/pull/67
- [x] https://github.com/etolbakov/excalidocker-rs
  - [ ] https://github.com/etolbakov/excalidocker-rs/pull/41
  - [ ] https://github.com/etolbakov/excalidocker-rs/pull/42
  - [ ] https://github.com/etolbakov/excalidocker-rs/pull/43
- [x] https://github.com/bmrlab/gendam
  - [x] https://github.com/bmrlab/gendam/pull/83
- [x] https://github.com/ast-grep/ast-grep
  - [x] https://github.com/ast-grep/ast-grep/pull/1338
  - [x] https://github.com/ast-grep/ast-grep/pull/1339

**Comment by yuchanns** [comment]
Happy Birthday! Keep rockin' that open-source vibe!

**Comment by dharanad** [comment]
Belated birthday wishes to you!. Keep doing all the good work @Xuanwo

**Comment by Xuanwo** [comment]
Most PRs have been merged, let's close and wait for next year.
